### ISSUE TITLE
Robot battery

### ISSUE THREAD

**Issue by ToMadoRe** [strands-project/scitos_robot#25]
We just experienced another severe problem with our battery. While running the waypoint patroller, the battery level shown on the small display on the robot platform indicated a very low battery level (blinking symbol). However, the rostopic /battery_state still published life_percentage with 79%. The cell voltage was down to approx. 2.4V. As expected, the robot died in the middle of its patrol run.

Not sure if this is related to our problem with a fully charged robot turning off abruptly when it stays on the charging station. Metralabs offered a firmware update. Was just wondering if anyone else experienced such a big discrepancy between ROS battery_state and the battery level indicated on the platform.

**Comment by ToMadoRe** [comment]
Just happened again:
Here the output of the /battery_state and a picture from the display on the robot platform:

```
---
header: 
  seq: 8656
  stamp: 
    secs: 1383734276
    nsecs: 645153870
  frame_id: ''
voltage: 22.7000007629
current: 3.27800011635
lifePercent: 72
lifeTime: -1
charging: False
powerSupplyPresent: False
cellVoltage: [2.6110000610351562, 2.8320000171661377, 2.8630001544952393, 2.6760001182556152, 2.947000026702881, 2.878000020980835, 2.9260001182556152, 2.9710001945495605]
```

![img_1022](https://f.cloud.github.com/assets/4250227/1481846/bbc46e14-46d1-11e3-99e1-b91340c79992.JPG)

Also, is it normal that the cellVoltage differs that much?
