### ISSUE TITLE
Replacing Battery in Linda?

### ISSUE THREAD

**Issue by Jailander** [strands-project/scitos_robot#73]
One of the battery cells in Linda is apparently damaged according to analysis ran by metralabs over this [mira tape](labe.felk.cvut.cz/~tkrajnik/miratapebattery.tape). @creuther what is the recommended course of actions here?

**Comment by creuther** [comment]
Unfortunately, the battery cell manufacturer specifically states that the battery cells have to be considered damaged if they drop below 2V. As this happened a couple of times, it is certainly safe to say that the battery needs to be replaced. I'll get you a quote for it.

Any heat issues that you may have with Linda might be exacerbated by the defective battery cell(s) as well, as they can produce a considerable amount of heat once they are defective.

**Comment by Jailander** [comment]
Yes we thought so... thank you for getting us the quotation.

About the heat issues we have been having them for a while now, I'm sure we can run a comparison on the inside temperature whilst charging before and after we change the batteries if that is useful for you.

**Comment by creuther** [comment]
If it is not too much of an effort then it would certainly help to exclude / identify that as one influencing factor. I am waiting to hear back from my boss and will let you know once I got the quote.

**Comment by creuther** [comment]
I finally got a quote. So my bosses tell me that a new battery is 950 Euro (net), not including shipping. As lithium batteries are unfortunately classified as dangerous goods (and also they are heavy), the shipping is usually not too cheap either.
So knowing that, please let me know what you want to do. If you want to get the replacement battery then I can have a formal quote sent to you and we can prepare everything in the mean time.

**Comment by cdondrup** [comment]
Since @marc-hanheide is sitting on our pot of gold, it would be up to him to decide. In general we seem to get a decent battery life out of Linda but it might be useful for future long-term tests. As we have seen on Werner it will most likely not fix the heat problem though...

@creuther how crucial is it from a technical point of view to replace the battery? Is there any danger in running the robot as it is now?

**Comment by marc-hanheide** [comment]
Exactly, I need to understand better what we would gain. Is there a real problem here, or is it just we would see getting 30 minutes more of runtime out of it? Also, I understood one cell was broken? So, is this for the exchange of all cell or just one?
Then, finally, it will be easier for us to buy this replacement while STRANDS is still running, so if we believe we'll need a new battery, then we ought to be buying it soon.

**Comment by marc-hanheide** [comment]
Also @tduckett should have a look at this.

**Comment by cdondrup** [comment]
I just remembered something, @creuther where does the broken cell diagnosis come from? If it is from the persistent error logs, it might be that it shows the broken pin we had in the battery connector at some point. The voltages themselves do look quite balanced:

```
header: 
  seq: 5719196
  stamp: 
    secs: 1460711806
    nsecs: 748912000
  frame_id: ''
voltage: 28.8010005951
current: 0.00900000054389
lifePercent: 100
lifeTime: -1
charging: True
powerSupplyPresent: True
cellVoltage: [3.6010000705718994, 3.6010000705718994, 3.5980002880096436, 3.6010000705718994, 3.6010000705718994, 3.5980002880096436, 3.6010000705718994, 3.6000001430511475]
```

So if it is from the persistent error log we might have "fixed" that already.
